
allowed.origins: http://localhost:8091

adminPath: api/v1

spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: postgres
          password: 123456
          url: jdbc:postgresql://localhost:5432/learn
          driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      maxFileSize: 5120MB
      maxRequestSize: 5120MB
  profiles:
      active: dev

# mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

UploadPath: D:/upload

Rtmp: rtmp://192.168.1.9/live

server:
  port: 8090
